### ISSUE TITLE
New function - move event from one calendar to other ( change calendar of event)

### ISSUE THREAD

**Issue by petrmikes** [0ihsan/mcal#4]
Hello Oihsan, Your app is really cool. Im using it daily. I have idea to new feature. It will be greate if shoud be added.

Change calendar event:
- Sometimes is necessary move event from one calendar to other. It will be greate to integrate like 

Example 

- actual event - Calendar personal -> need to move to calendar meetings
mcal changeCal personal meetings 'event with investors' 

Kind Regards

**Comment by 0ihsan** [comment]
moving **only the current event** would be enough for you?
otherwise, identifying which event to move might be a little cumbersome to implement.

**Comment by petrmikes** [comment]
Hello ,
thanks for quick reply. It will be better to move any of event. Not only actual. ( in case that event have any id it should be like mcal changecal personal meeting ID ; and ofcourse add id to (e.g) mcal show personal events detail


Many thanks
Ing. Petr Mikeš	 <https://www.mikysound.com/>
MikySound.com <https://www.mikysound.com/>
Phone: +420 774 990 659	CTO - Technical Director
E-mail:  ***@***.***>***@***.***  <https://www.mikysound.com/>	Czech Republic
Web: www.MikySound.com <https://www.mikysound.com/>	COMVERGA a.s.

**Comment by 0ihsan** [comment]
you can now do `mcal move newcalendar <eventid>`. but you can only change events within range[midnight, now]. 
you can `mcal list` to see the event ids. event ids are relative: 
- 0 is the most recent event (current or last). 
- 1 is one previous.
- 2 is two previous, etc.

**Comment by petrmikes** [comment]
Hello amazing. Working really fine.

One more idea. It will be great to have chance filter by :
mcal list <calendar> to show ids for specific calendar.

example:
	 mcal list –> show all events
	mcal list Meetings -> show events from calendar Meetings


and second point:
range [midnight , now] is little bit limited.
it should be great to have chance to specify like

mcal settings range -365D // range minus 1 year from now

or
mcal list Meetings -365D // show all events in range [-354D to now]

Hope that this ideas should match with you.

Thanks



Ing. Petr Mikeš	 <https://www.mikysound.com/>
MikySound.com <https://www.mikysound.com/>
Phone: +420 774 990 659	CTO - Technical Director
E-mail:  ***@***.***>***@***.***  <https://www.mikysound.com/>	Czech Republic
Web: www.MikySound.com <https://www.mikysound.com/>	COMVERGA a.s.

**Comment by petrmikes** [comment]
Do you think that what was written below should be possible to improve?

Petr


> 7. 6. 2024 v 9:34, ***@***.***:
> 
> ﻿Hello amazing. Working really fine.
> 
> One more idea. It will be great to have chance filter by :
> mcal list <calendar> to show ids for specific calendar.
> 
> example:
> 	 mcal list –> show all events
> 	mcal list Meetings -> show events from calendar Meetings
> 
> 
> and second point:
> range [midnight , now] is little bit limited.
> it should be great to have chance to specify like
> 
> mcal settings range -365D // range minus 1 year from now
> 
> or
> mcal list Meetings -365D // show all events in range [-354D to now]
> 
> Hope that this ideas should match with you.
> 
> Thanks
> 
>

**Comment by 0ihsan** [comment]
closing. see comment: https://github.com/0ihsan/mcal/pull/5
